///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class JeweleryRating {
/*
{
  "rate": 4.6,
  "count": 400
} 
*/

  double? rate;
  int? count;

  JeweleryRating({
    this.rate,
    this.count,
  });
  JeweleryRating.fromJson(Map<String, dynamic> json) {
    rate = json['rate']?.toDouble();
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rate'] = rate;
    data['count'] = count;
    return data;
  }
}

class Jewelery {
/*
{
  "id": 5,
  "title": "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
  "price": 695,
  "description": "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
  "category": "jewelery",
  "image": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
  "rating": {
    "rate": 4.6,
    "count": 400
  }
} 
*/

  int? id;
  String? title;
  int? price;
  String? description;
  String? category;
  String? image;
  JeweleryRating? rating;

  Jewelery({
    this.id,
    this.title,
    this.price,
    this.description,
    this.category,
    this.image,
    this.rating,
  });
  Jewelery.fromJson(Map<dynamic, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    price = json['price']?.toInt();
    description = json['description']?.toString();
    category = json['category']?.toString();
    image = json['image']?.toString();
    rating = (json['rating'] != null)
        ? JeweleryRating.fromJson(json['rating'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['price'] = price;
    data['description'] = description;
    data['category'] = category;
    data['image'] = image;
    if (rating != null) {
      data['rating'] = rating!.toJson();
    }
    return data;
  }
}
